file=open(".py","w+")
content=file.read()
print(content)
file.write("hello world\n")
file.write("good morning\n")
file.read()
print(content)
file.readlines()
file.close()

file=open("sample.txt","w+")
file.read()
data=file.read()
print(data)